@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Dec 05 13:36:38 -0800 2021
REM SW Build 3286242 on Wed Jul 28 13:10:47 MDT 2021
REM
REM IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_conv2d_behav -key {Behavioral:sim_1:Functional:tb_conv2d} -tclbatch tb_conv2d.tcl -protoinst "protoinst_files/bd_806f.protoinst" -protoinst "protoinst_files/test.protoinst" -log simulate.log"
call xsim  tb_conv2d_behav -key {Behavioral:sim_1:Functional:tb_conv2d} -tclbatch tb_conv2d.tcl -protoinst "protoinst_files/bd_806f.protoinst" -protoinst "protoinst_files/test.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
