# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_axi_dma_from_pl_to_ps_0/test_axi_dma_from_pl_to_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_dma_from_pl_to_ps_0 || ORIG_REF_NAME==test_axi_dma_from_pl_to_ps_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_dma_from_ps_to_pl_0 || ORIG_REF_NAME==test_axi_dma_from_ps_to_pl_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_smc_0/test_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_smc_0 || ORIG_REF_NAME==test_axi_smc_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_smc_1_0/test_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_smc_1_0 || ORIG_REF_NAME==test_axi_smc_1_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_smc_2_0/test_axi_smc_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_smc_2_0 || ORIG_REF_NAME==test_axi_smc_2_0} -quiet] -quiet

# IP: bd/test/ip/test_axis_data_fifo_0/test_axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axis_data_fifo_0 || ORIG_REF_NAME==test_axis_data_fifo_0} -quiet] -quiet

# IP: bd/test/ip/test_axis_data_fifo_0_0/test_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axis_data_fifo_0_0 || ORIG_REF_NAME==test_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_processing_system7_0_0 || ORIG_REF_NAME==test_processing_system7_0_0} -quiet] -quiet

# IP: bd/test/ip/test_rst_ps7_0_50M_0/test_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_rst_ps7_0_50M_0 || ORIG_REF_NAME==test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/test/ip/test_conv2D_0_0/test_conv2D_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_conv2D_0_0 || ORIG_REF_NAME==test_conv2D_0_0} -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/test_ooc.xdc
