# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/bd/test/ip/test_channel_add_0_0/test_channel_add_0_0.xci
# IP: The module: 'test_channel_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/ip/float_add/float_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==float_add || ORIG_REF_NAME==float_add} -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_channel_add_0_0/test_channel_add_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_channel_add_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/bd/test/ip/test_channel_add_0_0/test_channel_add_0_0.xci
# IP: The module: 'test_channel_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/ip/float_add/float_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==float_add || ORIG_REF_NAME==float_add} -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_channel_add_0_0/test_channel_add_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_channel_add_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
