# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0.xci
# IP: The module: 'test_axi_dma_from_ps_to_pl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/marc/Desktop/yolo/hardware/testing/test.srcs/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0.xci
# IP: The module: 'test_axi_dma_from_ps_to_pl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marc/Desktop/yolo/hardware/testing/test.gen/sources_1/bd/test/ip/test_axi_dma_from_ps_to_pl_0/test_axi_dma_from_ps_to_pl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_axi_dma_from_ps_to_pl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
